// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmCVXNZmFMufHQQWi4fWKpJ6RskMYP4bI',
    appId: '1:1055304403478:web:9f1da2d05c6408fb108337',
    messagingSenderId: '1055304403478',
    projectId: 'hrlynx-8521e',
    authDomain: 'hrlynx-8521e.firebaseapp.com',
    storageBucket: 'hrlynx-8521e.firebasestorage.app',
    measurementId: 'G-FY79QQPNKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3NkDfXayUoGWd4F0sghDCOFucHuEp1-0',
    appId: '1:1055304403478:android:a67e2f7fe10d0a65108337',
    messagingSenderId: '1055304403478',
    projectId: 'hrlynx-8521e',
    storageBucket: 'hrlynx-8521e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbxjPj2_HgfzlwQEJxjnKQVyd5gaEfbjM',
    appId: '1:1055304403478:ios:9e67fcb11180d6cb108337',
    messagingSenderId: '1055304403478',
    projectId: 'hrlynx-8521e',
    storageBucket: 'hrlynx-8521e.firebasestorage.app',
    iosBundleId: 'com.bdCalling.hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbxjPj2_HgfzlwQEJxjnKQVyd5gaEfbjM',
    appId: '1:1055304403478:ios:9e67fcb11180d6cb108337',
    messagingSenderId: '1055304403478',
    projectId: 'hrlynx-8521e',
    storageBucket: 'hrlynx-8521e.firebasestorage.app',
    iosBundleId: 'com.bdCalling.hr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmCVXNZmFMufHQQWi4fWKpJ6RskMYP4bI',
    appId: '1:1055304403478:web:f245240a8400643d108337',
    messagingSenderId: '1055304403478',
    projectId: 'hrlynx-8521e',
    authDomain: 'hrlynx-8521e.firebaseapp.com',
    storageBucket: 'hrlynx-8521e.firebasestorage.app',
    measurementId: 'G-N3QSN6E7B5',
  );
}
